### ISSUE TITLE
Running code in local

### ISSUE THREAD

**Issue by PranamyaJake** [akash-joshi/SiteSeer-Website-Changes-Tracker#8]
How do we run the code, giving npm start and opening in browser just gives hello world message. How do we configure web site urls.

**Comment by akash-joshi** [comment]
Hi ! You have to actually run it via Telegram. In `.env`, you enter the necessary keys. Find the documentation here : https://github.com/akash-joshi/SiteSeer-Website-Changes-Tracker/blob/master/ENV.md

**Comment by akash-joshi** [comment]
If you have any more issues, please do comment here.
